.\"  Copyright (C) 2007-2008 Nippon Telegraph and Telephone Corporation.
.\"  Written by Ryusuke Konishi <ryusuke@osrg.net>
.\"
.TH MKCP 8 "May 2008" "nilfs-utils version 2.0"
.SH NAME
mkcp \- make a NILFS2 checkpoint
.SH SYNOPSIS
.B mkcp
[\fIoptions\fP] [\fIdevice\fP]
.SH DESCRIPTION
.B mkcp
is a utility for making a checkpoint or snapshot for the NILFS2 file
system found in \fIdevice\fP.  When \fIdevice\fP is omitted, it tries
to find a NILFS2 file system from \fI/proc/mounts\fP.
.PP
This command is valid only for mounted NILFS2 file systems, and
will fail if the \fIdevice\fP has no active mounts.
.SH OPTIONS
.TP
.B \-s
Create a snapshot.
.TP
.B \-h
Display help message and exit.
.SH AUTHOR
Koji Sato <koji@osrg.net>
.SH AVAILABILITY
.B mkcp
is part of the nilfs-utils package and is available from
http://www.nilfs.org.
.SH SEE ALSO
.BR nilfs (8),
.BR lscp (1),
.BR chcp (8),
.BR rmcp (8),
.BR nilfs-tune (8).
