.\"  Copyright (C) 2007-2012 Nippon Telegraph and Telephone Corporation.
.\"  Written by Ryusuke Konishi <konishi.ryusuke@lab.ntt.co.jp>
.\"
.TH MKCP 8 "Apr 2014" "nilfs-utils version 2.2"
.SH NAME
mkcp \- make a NILFS2 checkpoint
.SH SYNOPSIS
.B mkcp
[\fIoptions\fP] [\fIdevice\fP]
.SH DESCRIPTION
.B mkcp
is a utility for making a checkpoint or snapshot for the NILFS2 file
system found in \fIdevice\fP.  When \fIdevice\fP is omitted, it tries
to find a NILFS2 file system from \fI/proc/mounts\fP.
.PP
This command is valid only for mounted NILFS2 file systems, and
will fail if the \fIdevice\fP has no active mounts.
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-snapshot\fR
Create a snapshot.
.TP
\fB\-p\fR, \fB\-\-print\fR
Print the checkpoint number when successfully created.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help message and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version and exit.
.SH AUTHOR
Koji Sato
.SH AVAILABILITY
.B mkcp
is part of the nilfs-utils package and is available from
http://nilfs.sourceforge.net.
.SH SEE ALSO
.BR nilfs (8),
.BR lscp (1),
.BR chcp (8),
.BR rmcp (8),
.BR nilfs-tune (8).
